<<<<<<< HEAD
# Remove the LoginSuccessHandler service definition if it exists at the top
# services:
#     App\Security\LoginSuccessHandler:
#         arguments:
#             $urlGenerator: '@router'
#             $security: '@security.helper' # Use security.helper service

security:
    enable_authenticator_manager: true # Ensure this is true (usually default)
=======
security:
>>>>>>> f5842df (Initial commit for Events branch)
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
<<<<<<< HEAD
            # Remove form_login section as AuthAuthenticator handles it
            # form_login:
            #     login_path: app_login
            #     check_path: app_login 
            #     # success_handler: App\Security\LoginSuccessHandler # Removed
            
            logout:
                path: app_logout
                target: app_login # Redirect back to login on logout
            
            # Explicitly use the custom authenticator
=======
            entry_point: App\Security\AuthAuthenticator  # 👈 Add this line
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /
>>>>>>> f5842df (Initial commit for Events branch)
            custom_authenticator: App\Security\AuthAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
