controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

google_redirect:
    path: /connect/google/check
    controller: App\Controller\OAuthController::googleRedirect
